package errorsf

var (
	SUCCESS                         = NewErrors("成功", "SUCCESS")
	NORMAL_FAIL_ERROR               = NewErrors("失败", "NORMAL_FAIL_ERROR")
	TOKEN_INVALID                   = NewErrors("令牌失效", "TOKEN_INVALID")
	TOKEN_GEN_ERROR                 = NewErrors("令牌生成失败", "TOKEN_GEN_ERROR")
	REFRESH_TOKEN_INVALID           = NewErrors("刷新令牌失效", "REFRESH_TOKEN_INVALID")
	REFRESH_TOKEN_TIME_ERROR        = NewErrors("未到刷新令牌时间", "REFRESH_TOKEN_TIME_ERROR")
	UN_MARSHAL_ERROR                = NewErrors("数据反序列化失败", "UN_MARSHAL_ERROR")
	UN_SUPPORT_FILE_TYPE            = NewErrors("不支持该文件类型", "UN_SUPPORT_FILE_TYPE")
	METHOD_NOT_ALLOWED              = NewErrors("不支持请求的方法", "METHOD_NOT_ALLOWED")
	INTERNAL_SERVER_ERROR           = NewErrors("内部错误", "INTERNAL_SERVER_ERROR")
	FILE_SYSTEM_ERROR               = NewErrors("读写文件出错", "FILE_SYSTEM_ERROR")
	PARAMS_REQUIRED                 = NewErrors("缺少必要的参数", "PARAMS_REQUIRED")
	PARAMS_ERROR                    = NewErrors("参数不正确", "PARAMS_ERROR")
	RECORD_DU_PLICATED              = NewErrors("记录重复", "RECORD_DU_PLICATED")
	DATABASE_SELECT_ERROR           = NewErrors("查询失败", "DATABASE_SELECT_ERROR")
	DATABASE_DELETE_ERROR           = NewErrors("删除失败", "DATABASE_DELETE_ERROR")
	DATABASE_UPDATE_ERROR           = NewErrors("更新失败", "DATABASE_UPDATE_ERROR")
	DATABASE_INSERT_ERROR           = NewErrors("创建失败", "DATABASE_INSERT_ERROR")
	CAN_NOT_MODIFY_ERROR            = NewErrors("不可修改", "CAN_NOT_MODIFY_ERROR")
	CAN_NOT_DELETE_ERROR            = NewErrors("不可删除", "CAN_NOT_DELETE_ERROR")
	DATA_VERIFY_ERROR               = NewErrors("数据校验失败", "DATA_VERIFY_ERROR")
	UN_LOGIN                        = NewErrors("未登录", "UN_LOGIN")
	UN_AUTH                         = NewErrors("无权限", "UN_AUTH")
	UN_LOGIN_IP_NOT_AUTH            = NewErrors("当前IP无权访问", "UN_LOGIN_IP_NOT_AUTH")
	DATA_NOT_FOUND                  = NewErrors("数据不存在", "DATA_NOT_FOUND")
	DATA_HAVEN_FOUND                = NewErrors("数据已存在", "DATA_HAVEN_FOUND")
	NOT_FOUND                       = NewErrors("未找到", "NOT_FOUND")
	NOT_FOUND_CONFIG                = NewErrors("未找到配置", "NOT_FOUND_CONFIG")
	LIMIT_RATE_ERROR                = NewErrors("请求太快了,请{{ .time }}后再试", "LIMIT_RATE_ERROR")
	PASSWORD_ERROR                  = NewErrors("密码错误", "PASSWORD_ERROR")
	INTERFACE_ERROR                 = NewErrors("接口错误", "INTERFACE_ERROR")
	FILE_UPLOAD_ERROR               = NewErrors("文件上传失败", "FILE_UPLOAD_ERROR")
	ACCOUNT_BANNED                  = NewErrors("账号已被禁用", "ACCOUNT_BANNED")
	EMAIL_SEND_ERROR                = NewErrors("邮件发送失败", "EMAIL_SEND_ERROR")
	EMAIL_NO_REGISTER               = NewErrors("邮箱未注册", "EMAIL_NO_REGISTER")
	EMAIL_BOUND_ERROR               = NewErrors("邮箱已绑定", "EMAIL_BOUND_ERROR")
	INVALID_VERIFICATION_CODE_ERROR = NewErrors("验证码错误", "INVALID_VERIFICATION_CODE_ERROR")
	FOLLOW_OWNER_ERROR              = NewErrors("不能关注自己", "FOLLOW_OWNER_ERROR")
	OSS_UPLOAD_FILE_ERROR           = NewErrors("OSS上传文件失败", "OSS_UPLOAD_FILE_ERROR")
	ACCOUNT_HAVEN_FOUND             = NewErrors("账号已存在", "ACCOUNT_HAVEN_FOUND")
	DATA_SYNC_ERROR                 = NewErrors("数据同步失败", "DATA_SYNC_ERROR")
	CHAT_EXCEED_LIMIT_ERROR         = NewErrors("聊天次数超出限制", "CHAT_EXCEED_LIMIT_ERROR")
	GET_JWT_BLACKLIST_FAILED        = NewErrors("获取JWT黑名单失败", "GET_JWT_BLACKLIST_FAILED")
)
